-- MySQL Script generated by MySQL Workbench
-- Sat Nov 26 14:54:20 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema portfolio_web
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema portfolio_web
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `portfolio_web` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `portfolio_web` ;

-- -----------------------------------------------------
-- Table `portfolio_web`.`pais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio_web`.`pais` ;

CREATE TABLE IF NOT EXISTS `portfolio_web`.`pais` (
  `PK_Pais` INT NOT NULL AUTO_INCREMENT,
  `pais` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`PK_Pais`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `portfolio_web`.`provincia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio_web`.`provincia` ;

CREATE TABLE IF NOT EXISTS `portfolio_web`.`provincia` (
  `PK_Provincia` INT NOT NULL AUTO_INCREMENT,
  `FK_Pais` INT NOT NULL,
  `provincia` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`PK_Provincia`),
  CONSTRAINT `FK_Pais_Provincia`
    FOREIGN KEY (`FK_Pais`)
    REFERENCES `portfolio_web`.`pais` (`PK_Pais`))
ENGINE = InnoDB
AUTO_INCREMENT = 49
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FK_Pais_Provincia_idx` ON `portfolio_web`.`provincia` (`FK_Pais` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `portfolio_web`.`municipio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio_web`.`municipio` ;

CREATE TABLE IF NOT EXISTS `portfolio_web`.`municipio` (
  `PK_Municipio` INT NOT NULL AUTO_INCREMENT,
  `FK_Provincia` INT NOT NULL,
  `municipio` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`PK_Municipio`),
  CONSTRAINT `FK_Provincia_Municipio`
    FOREIGN KEY (`FK_Provincia`)
    REFERENCES `portfolio_web`.`provincia` (`PK_Provincia`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FK_Provincia_Municipio_idx` ON `portfolio_web`.`municipio` (`FK_Provincia` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `portfolio_web`.`localidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio_web`.`localidad` ;

CREATE TABLE IF NOT EXISTS `portfolio_web`.`localidad` (
  `PK_Localidad` INT NOT NULL AUTO_INCREMENT,
  `FK_Municipio` INT NOT NULL,
  `localidad` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`PK_Localidad`),
  CONSTRAINT `FK_Municipio_Localidad`
    FOREIGN KEY (`FK_Municipio`)
    REFERENCES `portfolio_web`.`municipio` (`PK_Municipio`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FK_Municipio_Localidad_idx` ON `portfolio_web`.`localidad` (`FK_Municipio` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `portfolio_web`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio_web`.`usuario` ;

CREATE TABLE IF NOT EXISTS `portfolio_web`.`usuario` (
  `PK_Usuario` INT NOT NULL AUTO_INCREMENT,
  `correo` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `cuenta_activa` INT NOT NULL DEFAULT '1',
  PRIMARY KEY (`PK_Usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `correo_UNIQUE` ON `portfolio_web`.`usuario` (`correo` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `portfolio_web`.`persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio_web`.`persona` ;

CREATE TABLE IF NOT EXISTS `portfolio_web`.`persona` (
  `PK_Persona` INT NOT NULL AUTO_INCREMENT,
  `FK_Usuario_Persona` INT NOT NULL,
  `nombre_completo` VARCHAR(45) NULL DEFAULT NULL,
  `fecha_nacimiento` DATE NULL DEFAULT NULL,
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  `dni` VARCHAR(45) NULL DEFAULT NULL,
  `foto_perfil` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`PK_Persona`),
  CONSTRAINT `FK_Usuario_Persona`
    FOREIGN KEY (`FK_Usuario_Persona`)
    REFERENCES `portfolio_web`.`usuario` (`PK_Usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `dni_UNIQUE` ON `portfolio_web`.`persona` (`dni` ASC) VISIBLE;

CREATE INDEX `FK_Usuario_Persona_idx` ON `portfolio_web`.`persona` (`FK_Usuario_Persona` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `portfolio_web`.`domicilio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio_web`.`domicilio` ;

CREATE TABLE IF NOT EXISTS `portfolio_web`.`domicilio` (
  `PK_Domicilio` INT NOT NULL AUTO_INCREMENT,
  `FK_Persona` INT NOT NULL,
  `FK_Localidad` INT NOT NULL,
  `calle` VARCHAR(45) NULL DEFAULT NULL,
  `altura` VARCHAR(45) NULL DEFAULT NULL,
  `piso` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`PK_Domicilio`),
  CONSTRAINT `FK_Localidad_Domicilio`
    FOREIGN KEY (`FK_Localidad`)
    REFERENCES `portfolio_web`.`localidad` (`PK_Localidad`),
  CONSTRAINT `FK_Persona_Domicilio`
    FOREIGN KEY (`FK_Persona`)
    REFERENCES `portfolio_web`.`persona` (`PK_Persona`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FK_Persona_Domicilio_idx` ON `portfolio_web`.`domicilio` (`FK_Persona` ASC) VISIBLE;

CREATE INDEX `FK_Localidad_Domicilio_idx` ON `portfolio_web`.`domicilio` (`FK_Localidad` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `portfolio_web`.`educacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio_web`.`educacion` ;

CREATE TABLE IF NOT EXISTS `portfolio_web`.`educacion` (
  `PK_Educacion` INT NOT NULL AUTO_INCREMENT,
  `FK_Persona` INT NOT NULL,
  `titulo` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `fechaInicio` DATE NULL DEFAULT NULL,
  `fechaFin` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`PK_Educacion`),
  CONSTRAINT `FK_Persona_Educacion`
    FOREIGN KEY (`FK_Persona`)
    REFERENCES `portfolio_web`.`persona` (`PK_Persona`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FK_Persona_Educacion_idx` ON `portfolio_web`.`educacion` (`FK_Persona` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `portfolio_web`.`experiencia_laboral`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio_web`.`experiencia_laboral` ;

CREATE TABLE IF NOT EXISTS `portfolio_web`.`experiencia_laboral` (
  `PK_Experiencia_Laboral` INT NOT NULL AUTO_INCREMENT,
  `FK_Persona_Experiencia_Laboral` INT NOT NULL,
  `titulo` VARCHAR(45) NULL DEFAULT NULL,
  `subtitulo` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion` VARCHAR(240) NULL DEFAULT NULL,
  PRIMARY KEY (`PK_Experiencia_Laboral`),
  CONSTRAINT `FK_Experiencia_Persona`
    FOREIGN KEY (`FK_Persona_Experiencia_Laboral`)
    REFERENCES `portfolio_web`.`persona` (`PK_Persona`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FK_Experiencia_Persona_idx` ON `portfolio_web`.`experiencia_laboral` (`FK_Persona_Experiencia_Laboral` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `portfolio_web`.`referencia_laboral`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio_web`.`referencia_laboral` ;

CREATE TABLE IF NOT EXISTS `portfolio_web`.`referencia_laboral` (
  `PK_Referencia_Laboral` INT NOT NULL AUTO_INCREMENT,
  `FK_Experiencia` INT NOT NULL,
  `FK_Localidad` INT NOT NULL,
  `nombre_completo` VARCHAR(45) NULL DEFAULT NULL,
  `calle` VARCHAR(45) NULL DEFAULT NULL,
  `numero` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`PK_Referencia_Laboral`),
  CONSTRAINT `FK_Localidad_Experiencia`
    FOREIGN KEY (`FK_Localidad`)
    REFERENCES `portfolio_web`.`localidad` (`PK_Localidad`),
  CONSTRAINT `FK_Referencia_Experiencia`
    FOREIGN KEY (`FK_Experiencia`)
    REFERENCES `portfolio_web`.`experiencia_laboral` (`PK_Experiencia_Laboral`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FK_Experiencia_Referencia_idx` ON `portfolio_web`.`referencia_laboral` (`FK_Experiencia` ASC) VISIBLE;

CREATE INDEX `FK_Localidad_Experiencia_idx` ON `portfolio_web`.`referencia_laboral` (`FK_Localidad` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `portfolio_web`.`proyecto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio_web`.`proyecto` ;

CREATE TABLE IF NOT EXISTS `portfolio_web`.`proyecto` (
  `PK_Proyectos` INT NOT NULL AUTO_INCREMENT,
  `FK_Persona` INT NULL DEFAULT NULL,
  `FK_Referencia` INT NULL DEFAULT NULL,
  `tituloProyecto` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`PK_Proyectos`),
  CONSTRAINT `FK_Persona_Proyecto`
    FOREIGN KEY (`FK_Persona`)
    REFERENCES `portfolio_web`.`persona` (`PK_Persona`),
  CONSTRAINT `FK_Referencia_Proyecto`
    FOREIGN KEY (`FK_Referencia`)
    REFERENCES `portfolio_web`.`referencia_laboral` (`PK_Referencia_Laboral`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FK_Persona_Proyecto_idx` ON `portfolio_web`.`proyecto` (`FK_Persona` ASC) VISIBLE;

CREATE INDEX `FK_Referencia_Proyecto_idx` ON `portfolio_web`.`proyecto` (`FK_Referencia` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `portfolio_web`.`tecnologia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio_web`.`tecnologia` ;

CREATE TABLE IF NOT EXISTS `portfolio_web`.`tecnologia` (
  `PK_Tecnologia` INT NOT NULL AUTO_INCREMENT,
  `FK_Persona` INT NOT NULL,
  `nombre_tecnologia` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`PK_Tecnologia`),
  CONSTRAINT `FK_Prsona_Tecnologia`
    FOREIGN KEY (`FK_Persona`)
    REFERENCES `portfolio_web`.`persona` (`PK_Persona`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FK_Prsona_Tecnologia_idx` ON `portfolio_web`.`tecnologia` (`FK_Persona` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `portfolio_web`.`telefono_referencia_laboral`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio_web`.`telefono_referencia_laboral` ;

CREATE TABLE IF NOT EXISTS `portfolio_web`.`telefono_referencia_laboral` (
  `FK_Telefono_Referencia_Laboral` INT NOT NULL AUTO_INCREMENT,
  `FK_Referencia` INT NOT NULL,
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  `horarios` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`FK_Telefono_Referencia_Laboral`),
  CONSTRAINT `FK_Referencia_Telefono`
    FOREIGN KEY (`FK_Referencia`)
    REFERENCES `portfolio_web`.`referencia_laboral` (`PK_Referencia_Laboral`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FK_Referencia_Telefono_idx` ON `portfolio_web`.`telefono_referencia_laboral` (`FK_Referencia` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
